name: Crane Game workflow

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/main.yml'

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Check if crane_game file exists
        id: check_file
        run: |
          if [ -f "crane_game.py" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Run test_crane_game tests
        if: steps.check_file.outputs.exists == 'true'
        run: |
          pytest test_crane_game.py -v












